apiVersion: apps/v1
kind: Deployment
metadata:
  name: match
  labels:
    app: match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
        - name: match
          image: skcc017.azurecr.io/match:latest
          ports:
            - containerPort: 8080